---

version: "3.5"

services:
  postgres:
    image: postgres:${POSTGRES_IMAGE}
    container_name: postgres
    restart: always 
    volumes:
        - ./persistent-data/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${KEYCLOAK_DB}
        POSTGRES_USER: ${KEYCLOAK_DB_USER}
        POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
        TZ: ${TZ}
    ports:
      - "${KEYCLOAK_DB_PORT}:5432"
    networks:
        - dotstat_network

  keycloak:
    image: siscc/dotstatsuite-keycloak:${JS_RELEASE_TAG}
    container_name: keycloak
    depends_on:
        - postgres
    ports:
        - "${KEYCLOAK_PORT}:8080"
    volumes:
        - "./realm:/opt/jboss/import"
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    environment:
        - DB_VENDOR=POSTGRES
        - DB_SCHEMA=public
        - KEYCLOAK_USER=${KEYCLOAK_USER}
        - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
        - DB_USER=${KEYCLOAK_DB_USER}
        - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
        - DB_ADDR=postgres
        - DB_DATABASE=${KEYCLOAK_DB}
        - KEYCLOAK_IMPORT=/opt/jboss/import/tnso-realm.json
        - PROXY_ADDRESS_FORWARDING=true
    networks:
        - dotstat_network

networks:
  dotstat_network:
    name: dotstat_common_network