---

version: "3.5"
  
services:
  solr:
    image: solr:${SOLR_IMAGE}
    container_name: solr
    ports:
      - "${SOLR_PORT}:8983"
    networks:
      - dotstat_network
    entrypoint: 
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
    volumes: 
      - ./persistent-data/solr:/var/solr/data
    environment:
      - TZ=${TZ}

  redis:
    image: redis:${RADIS_IMAGE}
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./persistent-data/radis:/data
    environment:
      - TZ=${TZ}
    networks:
      - dotstat_network
  
  mongo:
    image: mongo:${MONGO_IMAGE}
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./persistent-data/mongo-db:/data/db
      - ./persistent-data/mongo-config:/data/configdb
    environment:
      - TZ=${TZ}
    networks:
      - dotstat_network

  config:
    image: siscc/dotstatsuite-config:${JS_RELEASE_TAG}
    container_name: config
    ports:
      - "5007:80"
    volumes:
      - "./config/assets:/opt/assets"
      - "./config/configs:/opt/configs"
      - "./config/i18n:/opt/i18n"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - BUCKET_PROVIDER=fs
      - DATA_DIR=/opt/
    networks:
      - dotstat_network

  data-lifecycle-manager:
    image: siscc/dotstatsuite-data-lifecycle-manager:${JS_RELEASE_TAG}
    container_name: data-lifecycle-manager
    ports:
      - "${DLM_PORT}:7002"
    environment:
      ROBOTS_POLICY: ${ROBOTS_POLICY_DLM}
      CONFIG_URL: http://config
      TRANSFER_SERVER_URL: "${PROTOCOL}://transfer-stathub-dev.nso.go.th/${TRANSFER_API_VERSION}"
      AUTHZ_SERVER_URL: "${PROTOCOL}://nsiauth-stathub-dev.nso.go.th/${AUTHZ_API_VERSION}"
      SFS_URL: "http://sfs/admin"
      SFS_API_KEY: ${API_KEY_SFS}
    volumes:
      - "./config/assets:/opt/build/assets"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dotstat_network

  data-explorer:
    image: siscc/dotstatsuite-data-explorer:${JS_RELEASE_TAG}
    container_name: data-explorer
    ports:
      - "${DE_PORT}:80"
    environment:
      CONFIG_URL: http://config
      AUTH_PROVIDER: ${AUTH_PROVIDER}
      GA_TOKEN: ${GA_TOKEN}
      GTM_TOKEN: ${GTM_TOKEN_DE}
      ROBOTS_POLICY: ${ROBOTS_POLICY_DE}
      SMTP_host: ${SMTP_HOST}
      SMTP_port: ${SMTP_PORT}
      SMTP_secure: ${SMTP_TLS}
      SMTP_auth_user: ${SMTP_USER}
      SMTP_auth_pass: ${SMTP_PASSWORD}
      MAIL_FROM: ${CONTACT_FROM}
      MAIL_TO: ${CONTACT_TO}
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
      CAPTCHA_SITE_KEY: ${CAPTCHA_SITE_KEY}
    volumes:
      - "./config/assets:/opt/build/assets"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dotstat_network

  share:
    image: siscc/dotstatsuite-share:${JS_RELEASE_TAG}
    container_name: share
    ports:
      - "${SHARE_PORT}:3007"
    environment:
      CONFIG_URL: http://config
      SITE_URL: "${PROTOCOL}://de-stathub-dev.nso.go.th/share"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${SHARE_DB_INDEX}
      SMTP_host: ${SMTP_HOST}
      SMTP_port: ${SMTP_PORT}
      SMTP_secure: ${SMTP_TLS}
      SMTP_auth_user: ${SMTP_USER}
      SMTP_auth_pass: ${SMTP_PASSWORD}
      MAIL_FROM: ${SHARE_MAIL_FROM}
      API_KEY: ${API_KEY_SHARE}
      SECRET_KEY: ${SECRET_KEY_SHARE}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dotstat_network

  data-viewer:
    image: siscc/dotstatsuite-data-viewer:${JS_RELEASE_TAG}
    container_name: data-viewer
    ports:
      - "${VIEWER_PORT}:80"
    environment:
      CONFIG_URL: http://config
      DEFAULT_TENANT: ${DEFAULT_TENANT}
      GA_TOKEN: ${GA_TOKEN}
      GTM_TOKEN: ${GTM_TOKEN_DV}
      ROBOTS_POLICY: ${ROBOTS_POLICY_DV}
    volumes:
      - "./config/assets:/opt/build/assets"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dotstat_network

  sfs:
    image: siscc/dotstatsuite-sdmx-faceted-search:${JS_RELEASE_TAG}
    container_name: sfs
    ports:
      - "${SFS_PORT}:80"
    restart: always
    environment:
      DEFAULT_TENANT: ${DEFAULT_TENANT}
      CONFIG_URL: http://config
      MONGODB_URL: mongodb://mongo:${MONGO_PORT}
      MONGODB_DATABASE: "sfs"
      SOLR_HOST: solr
      SOLR_PORT: ${SOLR_PORT}
      API_KEY: ${API_KEY_SFS}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dotstat_network

networks:
  dotstat_network:
    name: dotstat_common_network
