---

version: "3.5"

services:
    nsiws-training:
        image: siscc/sdmxri-nsi-maapi:${DOTNET_RELEASE_TAG}
        container_name: nsiws-training
        ports:
          - "${NSI_TRAINING_PORT}:80"
        environment:
            # Authentication configuration
            auth__enabled: ${AUTH_ENABLED}
            auth__allowAnonymous: "false"
            auth__authority: http://${KEYCLOAK_HOST}/auth/realms/${KEYCLOAK_REALM}
            auth__clientId: ${KEYCLOAK_CLIENT_ID}
            auth__requireHttps: "false"
            auth__validateIssuer: "false"
            auth__showPii: "true"
            # Authorization configuration
            mappingStore__Id__Default: "training" #Dataspace id
            DotStatSuiteCoreCommonDbConnectionString: Server=${COMMON_DB_SERVER};Database=${COMMON_DB};User=${COMMON_DB_RO_USER};Password=${COMMON_DB_RO_PWD};
            # Database configuration
            SQL_SERVER: ${STRUCT_DB_TRAINING_SERVER}
            SQL_DATABASE: ${STRUCT_DB_TRAINING}
            SQL_USER: ${STRUCT_DB_TRAINING_USER}
            SQL_PASSWORD: ${STRUCT_DB_TRAINING_PWD}
            # Dissemination database configuration
            disseminationDbConnection__dbType: SqlServer
            disseminationDbConnection__connectionString: Server=${DATA_DB_TRAINING_SERVER};Database=${DATA_DB_TRAINING};User=${DATA_DB_TRAINING_USER};Password=${DATA_DB_TRAINING_PWD};
            # MAAPI.NET configuration
            MA_SQL_USER: ${DB_SA_USER}
            MA_SQL_PASSWORD: ${DB_SA_PASSWORD}
            MA_ALWAYS_RESET: N
            # Other NSI WS configuration
            INSERT_NEW_ITEM_SCHEME_VALUES: "true"
            SENDER_ID: "training - DotStat v8"
            enableReleaseManagement: "true"
            TZ: ${TZ}
        depends_on:
          dbup-struct-training:
            condition: service_completed_successfully
        volumes:
          - "./logs:/app/logs"
        networks:
          - dotstat_network

    dbup-struct-training:
        image: siscc/dotstatsuite-dbup:${DOTNET_RELEASE_TAG}
        container_name: dbup-struct-training
        environment:
            EXECUTION_PARAMETERS: upgrade --connectionString Server=${STRUCT_DB_TRAINING_SERVER};Database=${STRUCT_DB_TRAINING};User=${DB_SA_USER};Password=${DB_SA_PASSWORD}; --mappingStoreDb --loginName ${STRUCT_DB_TRAINING_USER} --loginPwd ${STRUCT_DB_TRAINING_PWD} --force --alterPassword
            TZ: ${TZ}
        depends_on:
          db:
            condition: service_healthy
        networks:
          - dotstat_network

    dbup-data-training:
        image: siscc/dotstatsuite-dbup:${DOTNET_RELEASE_TAG}
        container_name: dbup-data-training
        environment:
            EXECUTION_PARAMETERS: upgrade --connectionString Server=${DATA_DB_TRAINING_SERVER};Database=${DATA_DB_TRAINING};User=${DB_SA_USER};Password=${DB_SA_PASSWORD}; --dataDb --loginName ${DATA_DB_TRAINING_USER} --loginPwd ${DATA_DB_TRAINING_PWD} --force --alterPassword
            TZ: ${TZ}
        depends_on:
          db:
            condition: service_healthy
        networks:
          - dotstat_network

networks:
    dotstat_network:
        name: dotstat_common_network